// Bundles the quiz ES modules into one self-registering IIFE for the embed.
//
// WHY NOT ESBUILD: this repo installs nothing. vercel.json sets
// installCommand "echo 'no dependencies'" and .github/workflows/ci.yml never
// runs npm ci, so any devDependency in the build path fails CI on the first
// push. The module graph is a handful of files deep with no external imports, so
// a resolver is overkill, concatenating in dependency order is enough.
//
// This strips comments and blank lines; it does NOT rename identifiers the way
// a real minifier would. The output is roughly a third smaller than the source
// and lands far inside the 150 KB budget, which is all the target asks for.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const QUIZ = join(ROOT, 'src/quiz');

export const SIZE_LIMIT = 150 * 1024;

// Dependency order, leaves first. sheet-parse imports nothing at all, and
// sheet-data is generated from the Google Sheet and feeds bundles.js.
const MODULES = [
  'sheet-parse.js',
  'sheet-data.js',
  'bundles.js',
  'matcher.js',
  'styles.js',
  'homegym-bundle-quiz.js'
];

/**
 * Turn one ES module into a bare script body.
 *
 * Comment stripping is deliberately conservative: it only removes `//` when it
 * is the first non-space thing on a line, and only removes `/* *\/` blocks that
 * open a line. Anything looser would eat the `//` in every `https://` URL in
 * bundles.js and silently corrupt fifteen product links.
 */
function toScriptBody(source) {
  return source
    // Drop the import statements, everything they name is already in scope.
    .replace(/^import\s[^;]*?from\s*['"][^'"]*['"];?[ \t]*$/gm, '')
    // Unwrap the export keyword from declarations.
    .replace(/^export\s+(const|let|function|class|async)\b/gm, '$1')
    // Drop re-export and default-export statements entirely.
    .replace(/^export\s+default\s+[^;]*;?[ \t]*$/gm, '')
    .replace(/^export\s*\{[^}]*\};?[ \t]*$/gm, '')
    // Line comments, only where the line begins with one.
    .replace(/^[ \t]*\/\/.*$/gm, '')
    // Block comments, only where one opens a line.
    .replace(/^[ \t]*\/\*[\s\S]*?\*\/[ \t]*$/gm, '')
    // Trailing whitespace, then runs of blank lines.
    .replace(/[ \t]+$/gm, '')
    .replace(/\n{2,}/g, '\n')
    .trim();
}

export function bundle() {
  const parts = MODULES.map((file) => toScriptBody(readFileSync(join(QUIZ, file), 'utf8')));

  const out = `/* Homegym.sg bundle quiz, generated by scripts/build-quiz.mjs. Do not edit. */
(function(){"use strict";
${parts.join('\n')}
})();
`;

  // A leaked import/export would throw "Unexpected token 'export'" at runtime,
  // in production, on the client's site. Fail the build here instead.
  const leaked = out.match(/^[ \t]*(import|export)\s/gm);
  if (leaked) {
    throw new Error(`bundler left ${leaked.length} module statement(s) in the output: ${leaked.join(', ')}`);
  }
  return out;
}

function main() {
  const code = bundle();
  const bytes = Buffer.byteLength(code);

  if (bytes > SIZE_LIMIT) {
    console.error(`build-quiz FAILED: ${(bytes / 1024).toFixed(1)} KB exceeds the ${SIZE_LIMIT / 1024} KB budget`);
    process.exit(1);
  }

  mkdirSync(join(ROOT, 'dist'), { recursive: true });
  writeFileSync(join(ROOT, 'dist/homegym-bundle-quiz.min.js'), code);
  console.log(
    `built dist/homegym-bundle-quiz.min.js  ${(bytes / 1024).toFixed(1)} KB ` +
    `(${((bytes / SIZE_LIMIT) * 100).toFixed(0)}% of the 150 KB budget)`
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
